# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LNCommonFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LNCommonFramework

    pod 'AFNetworking', '~> 3.0'
    pod 'FMDB'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'MJExtension'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'Masonry'
    #弹窗控件
    pod 'MBProgressHUD'

end
